apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "yelb.fullname" . }}-ui
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "yelb.fullname" . }}
      tier: frontend
  template:
    metadata:
      labels:
        app: {{ template "yelb.fullname" . }}
        tier: frontend
        release: {{ .Release.Name }}
        chart: {{ template "yelb.chart" . }}
    spec:
      containers:
      - name: yelb-ui
        image: {{ .Values.image.ui }}
        ports:
        - containerPort: 80
        env:
        - name: "APP_SERVER_HOSTNAME"
          value: {{ template "yelb.fullname" . }}-appserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "yelb.fullname" . }}-cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "yelb.fullname" . }}
      tier: cache
  template:
    metadata:
      labels:
        app: {{ template "yelb.fullname" . }}
        tier: cache
        release: {{ .Release.Name }}
        chart: {{ template "yelb.chart" . }}
    spec:
      containers:
      - name: redis-server
        image: {{ .Values.image.redis }}
        ports:
        - containerPort: 6379
        env:
        - name: "ALLOW_EMPTY_PASSWORD"
          value: "yes"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "yelb.fullname" . }}-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "yelb.fullname" . }}
      tier: backenddb
  template:
    metadata:
      labels:
        app: {{ template "yelb.fullname" . }}
        tier: backenddb
        release: {{ .Release.Name }}
        chart: {{ template "yelb.chart" . }}
    spec:
      containers:
      - name: {{ template "yelb.fullname" . }}-db
        image: {{ .Values.image.db }}
        ports:
        - containerPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "yelb.fullname" . }}-appserver
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "yelb.fullname" . }}
      tier: middletier
  template:
    metadata:
      labels:
        app: {{ template "yelb.fullname" . }}
        tier: middletier
        release: {{ .Release.Name }}
        chart: {{ template "yelb.chart" . }}
    spec:
      containers:
      - name: {{ template "yelb.fullname" . }}-appserver
        image: {{ .Values.image.appserver }}
        ports:
        - containerPort: 4567
        env:
        - name: "RACK_ENV"
          value: "custom"
        - name: "APP_SERVER_HOSTNAME"
          value: {{ template "yelb.fullname" . }}-appserver
        - name: "REDIS_SERVER_ENDPOINT"
          value: {{ template "yelb.fullname" . }}-redis-server
        - name: "YELB_DB_SERVER_ENDPOINT"
          value: {{ template "yelb.fullname" . }}-db
